<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AUCTION</name>
   <tag></tag>
   <elementGuidId>34a1f587-b47e-4466-b4ce-ceb93e075209</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/ul/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d939716a-6b17-44d3-abcd-5122b2833e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiListItem-root categoryItem MuiListItem-gutters MuiListItem-button</value>
      <webElementGuid>ebf40a99-9c41-43e7-ae60-2a8a28f96cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d47cfa51-d9f0-4c56-b11d-27de5823c934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>00347d0f-096b-4684-986f-2907afe0f362</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a3fa1af5-9d7d-47da-9773-4e9cae5b6907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AUCTION</value>
      <webElementGuid>d3634831-7796-4d4b-a8dd-853a8704e85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;categoryHeader noPrint&quot;]/ul[@class=&quot;customContainer&quot;]/div[@class=&quot;MuiButtonBase-root MuiListItem-root categoryItem MuiListItem-gutters MuiListItem-button&quot;]</value>
      <webElementGuid>8651fbef-44da-4bc9-aca6-c8d8822ab8de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/ul/div[4]</value>
      <webElementGuid>e7e964e8-cf70-4506-9005-419395f6ca88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ARTS &amp; CRAFTS &amp; HOBBIES'])[1]/following::div[1]</value>
      <webElementGuid>080b05d9-28f8-458e-9b3f-0ee11a162bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APPAREL'])[1]/following::div[2]</value>
      <webElementGuid>c9885c3e-c362-4484-8ab0-3b08f35a8b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUTOMOTIVE'])[1]/preceding::div[1]</value>
      <webElementGuid>a2d50471-7298-4742-b6f5-6bfe875ee207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BABY PRODUCTS'])[1]/preceding::div[2]</value>
      <webElementGuid>f3263b76-197a-4af3-aab4-5618c595d279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AUCTION']/parent::*</value>
      <webElementGuid>a943a879-a631-4263-a3ae-7adcf2283b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]</value>
      <webElementGuid>e2b8e254-45aa-4b46-9372-31a89a48c01d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'AUCTION' or . = 'AUCTION')]</value>
      <webElementGuid>b64fc61e-0a7f-4692-971a-49f80e6e8d81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
