<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Element_1660026841059</name>
   <tag></tag>
   <elementGuidId>184ba697-cfd8-4c4c-ac17-24319bcd0925</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
      <webElementGuid>c8766e43-f17e-4e14-98c8-d1b3dc5ef948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>xpath1660026841059</value>
      <webElementGuid>5427dc96-b466-4ee6-949d-486d00ac4f8b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
