<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Place Proxy Bid</name>
   <tag></tag>
   <elementGuidId>2e889934-503a-4a22-8647-fa4204b5a016</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.pvBidBox > form > div.biddingCnt.d-flex.justify-content-between.align-items-start > div.jss122.small.primButton > button.MuiButtonBase-root.MuiButton-root.MuiButton-contained</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='submit'])[10]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>20d24082-5bff-4b12-8f6b-35e22a84fbae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiButtonBase-root MuiButton-root MuiButton-contained</value>
      <webElementGuid>75f1cac9-0ae9-40d6-b6ca-401354278375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>42dff472-9b82-41ae-9684-4c3c78be5717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b7af9c4a-33e0-4129-aad2-00a9bace992a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Place Proxy Bid</value>
      <webElementGuid>0af7e9f6-1cd3-4884-bc24-6aebcfb04891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productView&quot;)/div[@class=&quot;d-flex flex-wrap&quot;]/div[@class=&quot;pvRt&quot;]/div[1]/div[@class=&quot;bdngByWrpr&quot;]/div[@class=&quot;bdPlcWrpr&quot;]/div[@class=&quot;pvBidBox&quot;]/form[1]/div[@class=&quot;biddingCnt d-flex justify-content-between align-items-start&quot;]/div[@class=&quot;jss122 small primButton&quot;]/button[@class=&quot;MuiButtonBase-root MuiButton-root MuiButton-contained&quot;]</value>
      <webElementGuid>71218276-29c1-4468-9c86-29c21bf3caae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='submit'])[10]</value>
      <webElementGuid>2f032ef5-bf99-4b9d-86d1-b2ee07aded8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='productView']/div/div[2]/div/div[3]/div/div[2]/form/div/div[2]/button</value>
      <webElementGuid>d2958d45-b739-4648-a0be-c512c71632ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Bid Amt'])[16]/following::button[1]</value>
      <webElementGuid>736a24ae-4a69-4034-b95c-bf4ab90156bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Bid Amt'])[15]/following::button[1]</value>
      <webElementGuid>930eaec8-3aa2-4f90-b07b-470553e2f1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buy now price'])[1]/preceding::button[1]</value>
      <webElementGuid>d25e3d83-ea68-4ed8-af26-20a252e52747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div/div[2]/button</value>
      <webElementGuid>0f912a51-6296-4f03-9eb3-daa84602448d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Place Proxy Bid' or . = 'Place Proxy Bid')]</value>
      <webElementGuid>887aea5e-1b73-42be-93ee-2a9a759b462c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
