<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter Bid Amt_wsprice</name>
   <tag></tag>
   <elementGuidId>b4e233fd-087f-4e82-b509-1ebd0c6a8747</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiInputBase-root.MuiOutlinedInput-root.Mui-focused.Mui-focused.MuiInputBase-formControl.MuiInputBase-marginDense.MuiOutlinedInput-marginDense > input[name=&quot;wsprice&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='wsprice'])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>178c1e14-d134-4edc-aee5-49de78aba7a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>119f3b1a-aece-4297-9077-b301d0acf1cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wsprice</value>
      <webElementGuid>4e59bcad-4e28-43ef-aff0-896bc838d681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Min Bid US $240.00</value>
      <webElementGuid>5ac76412-dafe-4a8e-b004-7d3b7ec676bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c1af5b66-523a-4d94-8825-3700b220074f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputMarginDense MuiOutlinedInput-inputMarginDense</value>
      <webElementGuid>2878be13-c474-4e17-8a46-7efce00a2b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productView&quot;)/div[@class=&quot;d-flex flex-wrap&quot;]/div[@class=&quot;pvRt&quot;]/div[1]/div[@class=&quot;bdngByWrpr&quot;]/div[@class=&quot;bdPlcWrpr&quot;]/div[@class=&quot;pvBidBox&quot;]/form[1]/div[@class=&quot;biddingCnt d-flex justify-content-between align-items-start&quot;]/div[1]/div[@class=&quot;customInput&quot;]/div[@class=&quot;MuiFormControl-root MuiTextField-root&quot;]/div[@class=&quot;MuiInputBase-root MuiOutlinedInput-root Mui-focused Mui-focused MuiInputBase-formControl MuiInputBase-marginDense MuiOutlinedInput-marginDense&quot;]/input[@class=&quot;MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputMarginDense MuiOutlinedInput-inputMarginDense&quot;]</value>
      <webElementGuid>adfadec1-36d9-4ec3-9349-d89f861ee1c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='wsprice'])[8]</value>
      <webElementGuid>651b56ef-b550-4513-a8c3-774001b9a573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='productView']/div/div[2]/div/div[3]/div/div[2]/form/div/div/div/div/div/input</value>
      <webElementGuid>6d3f35eb-e414-4974-989b-67d1267778d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/div/div/div/div/div/input</value>
      <webElementGuid>0cae06ca-3b10-42a9-8090-85eac724c9f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'wsprice' and @placeholder = 'Min Bid US $240.00' and @type = 'number']</value>
      <webElementGuid>441dacc8-ea56-4f39-8055-f2cf2c34c913</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
