<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Register</name>
   <tag></tag>
   <elementGuidId>ff5d4989-d4d4-44f4-9267-1b0f48a4a32e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/header/div/div[2]/div/ul[2]/li/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>110519a4-f26c-47b0-bf7f-a3c23c9a2104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>activeclassname</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>debc31da-525f-46da-9f00-3984bac4d18b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/registration</value>
      <webElementGuid>0e5651ae-dbf1-4fbc-8bf1-ed1a1fe1fcd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-current</name>
      <type>Main</type>
      <value>page</value>
      <webElementGuid>bdbcc729-5924-42f2-8b8a-606892789267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>active</value>
      <webElementGuid>05a5a7dc-742f-410f-95fd-a29041735171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Register</value>
      <webElementGuid>d942dea4-140a-4c0a-8a1a-1e73fb2bb9e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/header[@class=&quot;mainHeader noPrint&quot;]/div[@class=&quot;customContainer d-flex justify-content-between align-items-center h-100&quot;]/div[@class=&quot;menuRtOtr&quot;]/div[@class=&quot;headRt deskNav d-flex justify-content-end align-items-center&quot;]/ul[@class=&quot;d-flex justify-content-start align-items-center&quot;]/li[1]/a[@class=&quot;active&quot;]</value>
      <webElementGuid>5e54af8f-dbbf-4cf4-b9cc-a3b6ae57cdd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/div/div[2]/div/ul[2]/li/a[2]</value>
      <webElementGuid>4f090d1c-b39a-401c-b06a-0b89843273d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Register')]</value>
      <webElementGuid>8ba00e2a-122d-4ad0-bf39-8dce9369b69a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/following::a[1]</value>
      <webElementGuid>259fb8fb-e9df-4365-8d60-bd7b2084c381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select type of registration'])[1]/preceding::a[2]</value>
      <webElementGuid>ea85a625-0a1a-4efe-9fae-abf5c1fe20ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Register']/parent::*</value>
      <webElementGuid>9fcb47aa-c8b5-41b0-ad6a-b3227669a3a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/registration')]</value>
      <webElementGuid>a500c258-b090-46a4-bd42-42e82385ab07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>0068060f-294f-4e95-b89e-6ef83b017339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/registration' and (text() = 'Register' or . = 'Register')]</value>
      <webElementGuid>fbb89201-1f52-49e7-a2c5-dfe1fae33a8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
