<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_First NameFirst NameLast NameLast NameEmail AddressEmail AddressPhone NumberPhone NumberTax Exempt IDTax Exempt ID</name>
   <tag></tag>
   <elementGuidId>d7006b76-452f-4b58-b1aa-3581f68792ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div/div[2]/div[2]/div[2]/form/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.row</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f3024f03-bd63-4eb7-aa5a-62af2761132d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row</value>
      <webElementGuid>3d57f761-8971-4460-8067-0a3772c309c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>First NameFirst NameLast NameLast NameEmail AddressEmail AddressPhone NumberPhone NumberTax Exempt IDTax Exempt ID</value>
      <webElementGuid>da327817-9a79-4943-baea-4d755193bc42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;dashboard customContainer&quot;]/div[@class=&quot;d-flex justify-content-start&quot;]/div[@class=&quot;dashboardRt&quot;]/div[@class=&quot;dashboardInner myAccount&quot;]/div[@class=&quot;accountCnt&quot;]/form[1]/div[@class=&quot;accChild&quot;]/div[@class=&quot;row&quot;]</value>
      <webElementGuid>138d200f-505c-4613-a5fd-73007be1541b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div[2]/div[2]/div[2]/form/div/div</value>
      <webElementGuid>ab63234a-8b61-4c74-aff7-5dbd5de4ca5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile Details'])[1]/following::div[1]</value>
      <webElementGuid>517fbef6-4788-426d-9f95-06f5c7f7cfd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Notifications'])[2]/following::div[3]</value>
      <webElementGuid>7f991b96-3705-4093-bdd2-ffe87d38c557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div</value>
      <webElementGuid>41bb9044-0355-41d2-8871-33c6ec464f95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'First NameFirst NameLast NameLast NameEmail AddressEmail AddressPhone NumberPhone NumberTax Exempt IDTax Exempt ID' or . = 'First NameFirst NameLast NameLast NameEmail AddressEmail AddressPhone NumberPhone NumberTax Exempt IDTax Exempt ID')]</value>
      <webElementGuid>298c52d8-1d3f-4d08-a687-2cc5cd6418c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
