<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_account_circle</name>
   <tag></tag>
   <elementGuidId>7fff1d3e-8b55-4749-a745-6c653320d79d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/header/div[2]/div/ul/li[8]/button/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.small.material-icons</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>681fd45f-7df7-4ef3-bdbf-4356bf387428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>small material-icons</value>
      <webElementGuid>89c1e76c-a514-4b1e-a177-4d99e062560e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>account_circle</value>
      <webElementGuid>4f1f58ea-6297-4b20-928f-354f892d7a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/header[@class=&quot;mainHeader customContainer d-flex justify-content-between align-items-center noPrint&quot;]/div[2]/div[@class=&quot;headRt deskNav d-flex justify-content-start align-items-center&quot;]/ul[@class=&quot;d-flex justify-content-start align-items-center&quot;]/li[8]/button[@class=&quot;MuiButtonBase-root MuiButton-root MuiButton-text&quot;]/span[@class=&quot;MuiButton-label&quot;]/span[@class=&quot;small material-icons&quot;]</value>
      <webElementGuid>bf229ef9-eb65-4288-8e71-b5af23b125a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/header/div[2]/div/ul/li[8]/button/span/span</value>
      <webElementGuid>a868c630-882f-4bb1-b765-c40552dbb539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='shopping_cart'])[1]/following::span[4]</value>
      <webElementGuid>03ed6d78-c804-4d47-9b97-80253cfcc68c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='favorite'])[1]/following::span[9]</value>
      <webElementGuid>45418d59-08f9-4b6e-a68c-53b85365dc76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='menu'])[1]/preceding::span[2]</value>
      <webElementGuid>2684f10e-fff7-4d19-9246-39796ada8b2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='account_circle']/parent::*</value>
      <webElementGuid>171a8390-f2be-4cc4-99be-87155bd79680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/button/span/span</value>
      <webElementGuid>6763ae2a-e43a-4c2c-83c3-d518ad936e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'account_circle' or . = 'account_circle')]</value>
      <webElementGuid>97f3a921-9773-4f5a-9c89-c173f9fe8851</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
