<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm Email Address_confirm_email</name>
   <tag></tag>
   <elementGuidId>a68d536d-edf0-42c2-8161-49e3f8ee555c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='confirm_email']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;confirm_email&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42f99dce-de9b-4192-8cba-e1a6123d21ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3d185c30-0c75-4a19-9d0b-334ea45e8168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>confirm_email</value>
      <webElementGuid>1f780f94-cefc-4f82-8e54-3d915e8e2685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Your Email Address</value>
      <webElementGuid>84cfe552-81c2-4d31-8852-fe835b01fded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>79660759-f1ad-4f03-95e7-74a8979152e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input</value>
      <webElementGuid>4c4d61cc-4fb4-4226-87ef-df08046b6896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/section[@class=&quot;container-lg&quot;]/div[@class=&quot;registration&quot;]/div[@class=&quot;plBox&quot;]/div[@class=&quot;login regContainer&quot;]/div[@class=&quot;addUserModal&quot;]/div[@class=&quot;fspBody&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-sm-6&quot;]/div[@class=&quot;customInput&quot;]/div[@class=&quot;MuiFormControl-root MuiTextField-root&quot;]/div[@class=&quot;MuiInputBase-root MuiOutlinedInput-root MuiInputBase-formControl&quot;]/input[@class=&quot;MuiInputBase-input MuiOutlinedInput-input&quot;]</value>
      <webElementGuid>5941bf08-831b-47cd-ab0b-d6f435e21a3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='confirm_email']</value>
      <webElementGuid>d49f23df-3c1c-4ab5-88e4-388d9e63485a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/div/div/div[2]/div[2]/div/div/div[4]/div/div/div/input</value>
      <webElementGuid>da186a6d-6e8d-474d-b7b7-20fc63c550dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>14878cb2-66d1-4abe-bcd9-6535a421cd98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'confirm_email' and @placeholder = 'Enter Your Email Address' and @type = 'email']</value>
      <webElementGuid>0ff6fd04-fc14-4718-93e1-35817b9a9f12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
