<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip code_zip</name>
   <tag></tag>
   <elementGuidId>f7bd8da8-6a5e-40ba-a3b6-eb5600609fce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='zip']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;zip&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b0e5599-6b36-4853-8d40-94035f9d3a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b44fdb11-ff5c-4a5d-ab3a-a72751fa1da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>zip</value>
      <webElementGuid>c678f435-590f-4694-9ca5-f7202f7cef1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Your post box number</value>
      <webElementGuid>43821c9b-d606-4daa-859e-8e8ea16abd5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5cde7fcf-1eb3-42e0-9de4-e0ddef295e84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input</value>
      <webElementGuid>ca09d1a0-26ed-4d94-b794-34d772ef06af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/section[@class=&quot;container-lg&quot;]/div[@class=&quot;registration&quot;]/div[@class=&quot;plBox&quot;]/div[@class=&quot;login regContainer&quot;]/div[@class=&quot;addUserModal&quot;]/div[@class=&quot;fspBody&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-12 col-sm-3&quot;]/div[@class=&quot;customInput&quot;]/div[@class=&quot;MuiFormControl-root MuiTextField-root&quot;]/div[@class=&quot;MuiInputBase-root MuiOutlinedInput-root MuiInputBase-formControl&quot;]/input[@class=&quot;MuiInputBase-input MuiOutlinedInput-input&quot;]</value>
      <webElementGuid>5ccf3285-053e-49e3-b527-97fd143eb3cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='zip']</value>
      <webElementGuid>e6583ae3-9479-4cd7-81c7-eba91230dddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/section/div/div/div[2]/div[2]/div/div/div[12]/div/div/div/input</value>
      <webElementGuid>c075c5f0-fe09-428f-a405-8b20492d6241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div/div/input</value>
      <webElementGuid>1e203553-423c-4dca-9cf9-af4a107c06e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'zip' and @placeholder = 'Enter Your post box number' and @type = 'text']</value>
      <webElementGuid>cd6ff7e2-8b1b-4b41-9d62-2f43e80880bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
